site_name: ImageryClient
site_url: https://caveconnectome.github.io/ImageryClient/
repo_url: https://github.com/CAVEconnectome/ImageryClient/
repo_name: CAVEconnectome/ImageryClient

theme:
  name: material
  language: en
  logo: images/logo-cleanest.png
  favicon: images/logo-cleanest.png
  palette:
    primary: blue grey
    accent: deep orange
  font:
    text: Bitter
    code: Inconsolata
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.tabs # toggle to mainly use top nav
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections 
    - navigation.footer
    - navigation.prune
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
nav:
  - ImageryClient: index.md
  - Tutorial:
    - Getting Started: getting_started.md
    - Downloading Data: images.md
    - Generating Overlays: overlays.md
  - Function Reference:
    - reference/imagery_client.md
    - reference/composite_overlays.md
markdown_extensions:
  - attr_list
  - admonition
plugins:
  - caption:
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://numpy.org/doc/stable/objects.inv
            - https://pandas.pydata.org/pandas-docs/stable/objects.inv
            - https://networkx.org/documentation/stable/objects.inv
            - https://docs.scipy.org/doc/scipy/objects.inv
            - https://requests.readthedocs.io/en/latest/objects.inv
          paths: [.]
          options:
            show_source: false
            docstring_style: numpy
            docstring_section_style: table # list, table, spacy
            docstring_options:
              ignore_init_summary: false
            merge_init_into_class: true
            allow_section_blank_line: false
            show_root_heading: false
            show_root_toc_entry: false
            show_object_full_path: false
            show_symbol_type_heading: false # whether to show "meth/func/etc" in the page
            show_symbol_type_toc: true # whether to show "meth/func/etc" in the toc
            signature_crossrefs: true # https://mkdocstrings.github.io/python/usage/configuration/signatures/#signature_crossrefs
            members_order: alphabetical # can be source
            group_by_category: true  # order is attributes, classes, functions, modules
            summary: true
            show_if_no_docstring: false
            show_docstring_attributes: false
            annotations_path: brief # https://mkdocstrings.github.io/python/usage/configuration/signatures/#annotations_path
            show_signature: true
            separate_signature: false
            show_signature_annotations: false
            unwrap_annotated: false # https://mkdocstrings.github.io/python/usage/configuration/signatures/#unwrap_annotated
            heading_level: 3
            inherited_members: true
            show_docstring_warns : false
            show_docstring_raises : false
            show_root_full_path : true
