project:
  title: "ImageryClient"
  type: website
  output-dir: .

website:
  title: "ImageryClient"
  page-navigation: true
  navbar:
    left:
      - text: Getting Started
        href: getting_started.qmd
      - text: Tutorials
        menu:
          - tutorials/images.qmd
          - tutorials/overlays.qmd
      - href: reference/index.qmd
        text: Function Reference
    tools:
      - icon: github
        text: Github
        href: http://github.com/AllenInstitute/ImageryClient

format:
  html:
    toc: true

theme:
  - flatly
   
metadata-files:
  - _sidebar.yml

quartodoc:
  style: 'pkgdown'
  title: ''
  sidebar: _sidebar.yml
  dir: reference
  out_index: _api_index.qmd
  package: imageryclient
  parser: numpy
  sections:
    - title: ImageryClient
      desc: Main functions for downloading imagery and segmentation data.
      contents:
        - imagery.bounds_from_center
        - name: imagery.ImageryClient
          children: flat 
    - title: Compositing
      desc: Functions for generating overlay visualizations of images and segmentation.
      contents:
      - composite.stack_images
      - composite.composite_overlay
    - title: Utilities
      desc: Additional utility functions for working with imagery and segmentation data.
      contents:
      - utils.rescale_to_bounds
      - utils.binary_seg_outline
      - utils.mask_image
      - utils.segmentation_masks

